var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/notebook/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__3964bdab._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_795e95ae._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5f98963d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a64655ed._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__d78afe7c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_notebook_[id]_page_actions_4878ed9c.js")
R.m(98969)
module.exports=R.m(98969).exports
