var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/co-writer/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__c65bf8e3._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_10cefb58._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5f98963d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a64655ed._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__d78afe7c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_co-writer_page_actions_ba411f44.js")
R.m(84233)
module.exports=R.m(84233).exports
